export const PRODUCTS = [
  // Coffee
  {
    id: 'irish-coffee',
    category: 'coffee',
    title: 'Irish coffee',
    description: 'Fragrant black coffee with Jameson Irish whiskey and whipped milk',
    price: 7.0,
    image: '/img/catalog/coffee/irish-coffee.jpg',
  },
  {
    id: 'kahlua-coffee',
    category: 'coffee',
    title: 'Kahlua coffee',
    description: 'Classic coffee with milk and Kahlua liqueur under a cap of frothed milk',
    price: 7.0,
    image: '/img/catalog/coffee/kahlua-coffee.jpg',
  },
  {
    id: 'honey-raf',
    category: 'coffee',
    title: 'Honey raf',
    description: 'Espresso with frothed milk, cream and aromatic honey',
    price: 5.5,
    image: '/img/catalog/coffee/honey-raf.jpg',
  },
  {
    id: 'ice-cappuccino',
    category: 'coffee',
    title: 'Ice cappuccino',
    description: 'Cappuccino with soft thick foam in summer version with ice',
    price: 5.0,
    image: '/img/catalog/coffee/ice-cappuccino.jpg',
  },
  {
    id: 'espresso',
    category: 'coffee',
    title: 'Espresso',
    description: 'Classic black coffee',
    price: 4.5,
    image: '/img/catalog/coffee/espresso.jpg',
  },
  {
    id: 'latte',
    category: 'coffee',
    title: 'Latte',
    description: 'Espresso coffee with the addition of steamed milk and dense milk foam',
    price: 5.5,
    image: '/img/catalog/coffee/latte.jpg',
  },
  {
    id: 'latte-macchiato',
    category: 'coffee',
    title: 'Latte macchiato',
    description: 'Espresso with frothed milk and chocolate',
    price: 5.5,
    image: '/img/catalog/coffee/latte-macchiato.jpg',
  },
  {
    id: 'coffee-with-cognac',
    category: 'coffee',
    title: 'Coffee with cognac',
    description: 'Fragrant black coffee with cognac and whipped cream',
    price: 6.5,
    image: '/img/catalog/coffee/coffee-with-cognac.jpg',
  },

  // Tea
  {
    id: 'moroccan',
    category: 'tea',
    title: 'Moroccan',
    description: 'Fragrant black tea with the addition of tangerine, cinnamon, honey, lemon and mint',
    price: 4.5,
    image: '/img/catalog/tea/moroccan.jpg',
  },
  {
    id: 'ginger',
    category: 'tea',
    title: 'Ginger',
    description: 'Original black tea with fresh ginger, lemon and honey',
    price: 5.0,
    image: '/img/catalog/tea/ginger.jpg',
  },
  {
    id: 'cranberry',
    category: 'tea',
    title: 'Cranberry',
    description: 'Invigorating black tea with cranberry and honey',
    price: 5.0,
    image: '/img/catalog/tea/cranberry.jpg',
  },
  {
    id: 'sea-buckthorn',
    category: 'tea',
    title: 'Sea buckthorn',
    description: 'Toning sweet black tea with sea buckthorn, fresh thyme and cinnamon',
    price: 5.5,
    image: '/img/catalog/tea/sea-buckthorn.jpg',
  },

  // Dessert
  {
    id: 'marble-cheesecake',
    category: 'dessert',
    title: 'Marble cheesecake',
    description: 'Philadelphia cheese with lemon zest on a light sponge cake and red currant jam',
    price: 3.5,
    image: '/img/catalog/dessert/marble-cheesecake.jpg',
  },
  {
    id: 'red-velvet',
    category: 'dessert',
    title: 'Red velvet',
    description: 'Layer cake with cream cheese frosting',
    price: 4.0,
    image: '/img/catalog/dessert/red-velvet.jpg',
  },
  {
    id: 'cheesecakes',
    category: 'dessert',
    title: 'Cheesecakes',
    description: 'Soft cottage cheese pancakes with sour cream and fresh berries and sprinkled with powdered sugar',
    price: 4.5,
    image: '/img/catalog/dessert/cheesecakes.jpg',
  },
  {
    id: 'creme-brulee',
    category: 'dessert',
    title: 'Creme brulee',
    description: 'Delicate creamy dessert in a caramel basket with wild berries',
    price: 4.0,
    image: '/img/catalog/dessert/creme-brulee.jpg',
  },
  {
    id: 'pancakes',
    category: 'dessert',
    title: 'Pancakes',
    description: 'Tender pancakes with strawberry jam and fresh strawberries',
    price: 4.5,
    image: '/img/catalog/dessert/pancakes.jpg',
  },
  {
    id: 'honey-cake',
    category: 'dessert',
    title: 'Honey cake',
    description: 'Classic honey cake with delicate custard',
    price: 4.5,
    image: '/img/catalog/dessert/honey-cake.jpg',
  },
  {
    id: 'chocolate-cake',
    category: 'dessert',
    title: 'Chocolate cake',
    description: 'Cake with hot chocolate filling and nuts with dried apricots',
    price: 5.5,
    image: '/img/catalog/dessert/chocolate-cake.jpg',
  },
  {
    id: 'black-forest',
    category: 'dessert',
    title: 'Black forest',
    description: 'A combination of thin sponge cake with cherry jam and light chocolate mousse',
    price: 6.5,
    image: '/img/catalog/dessert/black-forest.jpg',
  },
];
